---
# The following setup is for the logging system. For information on how to change this
# see 
Serilog:
  Using:
  MinimumLevel: 
    Default: Information
  Override: 
    Microsoft: Warning
    System: Warning
  Enrich:
    - FromLogContext
    - WithProcessId
    - WithThreadId
  WriteTo:
    -
      Name: File
      Args:
        path: logs/dcscribe.log
GameServers:
  - 
    # Replace the following example fields with those used by your server and database
    Name: RurouniJones Bestest Server
    # Used in discord commands so keep this unique across your gameservers
    ShortName: RBS
    Database:
      # Make sure you set your pg_hba.conf file if you are not connecting over localhost
      # https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
      Host: rbs.example.com
      Port: 5432
      Name: rbs_database
      Username: dcscribe
      Password: this_is_a_password
    Rpc:
      Host: rbs.example.com
      # This is the default port
      Port: 50051
  # You can specify multiple game servers and have one DCScribe instance handle all of them
  - 
    # Replace the following example fields with those used by your server and database
    Name: RurouniJones Worstest Server
    # Used in discord commands so keep this unique across your gameservers
    ShortName: RWS
    Database:
      # Make sure you set your pg_hba.conf file if you are not connecting over localhost
      # https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
      Host: rws.example.com
      Port: 5432
      Name: rws_database
      Username: dcscribe
      Password: this_is_a_password
    Rpc:
      Host: rws.example.com
      # This is the default port
      Port: 50051